version: '3'
services:
  level-up:
    build: .
    container_name: level-up-app
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - CORS_ORIGIN=*
    volumes:
      - ./server/data.json:/app/server/data.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    command: >
      sh -c "ls -la /app/client/build && npm start" 